/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:d8327c06-8227-4e14-9539-49e685c2dcd4",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_WpuSDfxYd",
    "aws_user_pools_web_client_id": "3vberl3fth8bbouuk2rago76eg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_UPPERCASE",
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "plantdiseasestoragebucket3ffb5-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_cloud_logic_custom": [
        {
            "name": "plantdiseaseapi",
            "endpoint": "https://nhp9p4cxn3.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
